version: '3'
services:
  rabbit:
    container_name: dev_rabbit
    hostname: rabbit
    image: rabbitmq:3.8.0-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=DEFAULT_PW
#cZTQ0BVnHRZxLMfBrkcRH1bU
    ports:
      - "5672:5672"
      - "15672:15672"
